services:
  yarilo:
    image: typicalam/yarilo:latest-hardware
    command: --log_level=trace --battery_file=/app/battery/battery_level --oid_file=/app/data/oid.txt --save_path=/app/saves --db_file=/app/db/yarilo_database.db --iface=wlan1
    volumes:
      - /opt/saves:/app/saves
      - /opt/db:/app/db
      - ./pcap:/tmp/pcap
      - /tmp:/app/battery
    network_mode: host 
    cap_add:
      - NET_ADMIN

  yarilo-front:
    image: typicalam/yarilo-front:latest
  
  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - yarilo
      - yarilo-front

  python-server:
    image: python:3.14-rc-slim
    working_dir: /saves
    command: python3 -m http.server 2137
    volumes:
      - /opt/saves:/saves/download
    depends_on:
      - nginx

