# syntax=docker/dockerfile:1

FROM phusion/baseimage:focal-1.2.0

# Copy the binaries and libs from the builder
COPY --from=typicalam/yarilo-build:v0.1 /app/deps /app/deps

# Prepare runtime deps
RUN apt-get update \
	&& apt-get install -y --no-install-recommends build-essential ninja-build libpcap-dev libssl-dev \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

# Create the run script
COPY <<EOF ./run.sh
#!/bin/bash
export PATH="/app/deps/bin:$PATH"
protoc -I /app/src/protos --grpc_out=/app/src/backend/src --plugin=protoc-gen-grpc=$(which grpc_cpp_plugin) /app/src/protos/packets.proto && \
protoc -I /app/src/protos --cpp_out=/app/src/backend/src /app/src/protos/packets.proto && \
/app/deps/bin/cmake -DCMAKE_PREFIX_PATH=/app/deps -G Ninja -B /app/build /app/src/backend && \
ninja -C /app/build && \
/app/build/yarilo \$*
EOF
