# syntax=docker/dockerfile:1

FROM phusion/baseimage:jammy-1.0.1 as build

# Prepare deps
RUN apt-get update \
	&& apt-get install -y --no-install-recommends build-essential=12.9ubuntu3 ninja-build=1.10.1-1 curl=7.81.0-1ubuntu1.15 git=1:2.34.1-1ubuntu1.10 libpcap-dev=1.10.1-4build1 libssl-dev=3.0.2-0ubuntu1.13 \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /app/deps

# Download a newer cmake than the ubuntu one (it's laughably old)  
RUN curl -L https://github.com/Kitware/CMake/releases/download/v3.19.6/cmake-3.19.6-Linux-x86_64.sh -o cmake-linux.sh \
	&& sh cmake-linux.sh --prefix=/app/deps --exclude-subdir --skip-license \
	&& rm cmake-linux.sh

# Download and install grpc
RUN git clone --recurse-submodules -b v1.60.0 --depth 1 --shallow-submodules https://github.com/grpc/grpc /opt/grpc \
	&& mkdir /opt/grpc/cmake/build \
	&& /app/deps/bin/cmake -B /opt/grpc/cmake/build -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/app/deps /opt/grpc \
	&& make -C /opt/grpc/cmake/build -j 4 \
	&& make -C /opt/grpc/cmake/build install \
	&& rm -rf /opt/grpc

# Download and install libtins
RUN git clone --recurse-submodules -b v4.5 --depth 1 --shallow-submodules https://github.com/mfontanini/libtins /opt/libtins \
	&& mkdir /opt/libtins/build \
	&& /app/deps/bin/cmake -B /opt/libtins/build -DLIBTINS_ENABLE_CXX11=1 -DLIBTINS_ENABLE_ACK_TRACKER=0 -DCMAKE_INSTALL_PREFIX=/app/deps /opt/libtins \
	&& make -C /opt/libtins/build -j 4 \
	&& make -C /opt/libtins/build install \
	&& rm -rf /opt/libtins

# Download the envoy proxy
RUN curl -L https://github.com/envoyproxy/envoy/releases/download/v1.29.0/envoy-1.29.0-linux-x86_64 -o /app/deps/bin/envoy \
	&& chmod +x /app/deps/bin/envoy

# Real build
FROM phusion/baseimage:jammy-1.0.1

# Prepare runtime deps
RUN apt-get update \
	&& apt-get install -y --no-install-recommends build-essential=12.9ubuntu3 ninja-build=1.10.1-1 libpcap-dev=1.10.1-4build1 libssl-dev=3.0.2-0ubuntu1.13 \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

# Copy the binaries and libs from the builder
COPY --from=build /app/deps /app/deps

# Create the run script
COPY <<EOF ./run.sh
#!/bin/bash
export PATH="/app/deps/bin:$PATH"
protoc -I /app/src/protos --grpc_out=/app/src/backend/src --plugin=protoc-gen-grpc=$(which grpc_cpp_plugin) /app/src/protos/packets.proto && \
protoc -I /app/src/protos --cpp_out=/app/src/backend/src /app/src/protos/packets.proto && \
/app/deps/bin/cmake -DCMAKE_PREFIX_PATH=/app/deps -G Ninja -B /app/build /app/src/backend && \
ninja -C /app/build && \
/app/build/sniffsniff \$*
EOF
